### ISSUE TITLE
Generate API documentation

### ISSUE THREAD

**Issue by lwasylow** [BBVA/mirrorgate#7]
Hi 
I 'm not entirely sure how to generate API docs, readme says about running test but in fairness I'm more database person so not really understand.
Managed to run and start dashboard however I'm using a TFS so wonder if I could leverage API to collect the data.

**Comment by alfonso-presa** [comment]
I understand you are willing to connect TFS (Team Fundation Server?) to MirrorGate, I guess mainly for Build and may be Sprint tracking. Unfortunatelly there's no such a thing as API documentation jet... Eventhough it can be "easilly" seen in the sources:
- Build collection is very straight forward, in fact you can just push the information through a curl command. We used to use something like this in our pipelines right before we developed the jenkins plugin:
```
    echo '{'    > _msg.json
    echo '    "number" : "${env.BUILD_NUMBER}",'    >> _msg.json
    echo '    "timestamp" : ' >> _msg.json
    date +%s >> _msg.json
    echo , >> _msg.json
    echo '    "buildUrl" : "${env.BUILD_URL}",'   >> _msg.json
    echo '    "buildStatus" : "$buildStatus",' >> _msg.json
    echo '    "projectName" : "MirrorGate",'  >> _msg.json
    echo '    "repoName" : "mirrorgate-app",' >> _msg.json
    echo '    "branch" : "${env.GIT_BRANCH}"'  >> _msg.json
    echo '}'    >> _msg.json

    curl -H "Content-Type: application/json" -X POST -d @_msg.json http://[your.server.corp]/mirrorgate/builds
```
The entry point of that service is this one: https://github.com/BBVA/mirrorgate/blob/master/mirrorgate-api/src/main/java/com/bbva/arq/devops/ae/mirrorgate/api/BuildController.java#L96

This is the model that the service receives:
https://github.com/BBVA/mirrorgate/blob/master/mirrorgate-api/src/main/java/com/bbva/arq/devops/ae/mirrorgate/model/Build.java

Note you can use the buildStatus to control the different possible states of a build: https://github.com/BBVA/mirrorgate/blob/master/mirrorgate-api/src/main/java/com/bbva/arq/devops/ae/mirrorgate/support/BugStatus.java#L24

- For user story collection it's a little bit more complicated. You also have to post the information but the model is more messy and may be a little bit bound to Jira (the tool be use). I think it would be easier if you check how the jira collector performs it's work:
Here https://github.com/BBVA/mirrorgate-jira-stories-collector/blob/master/src/main/java/com/bbva/arq/devops/ae/mirrorgate/collectors/jira/api/SprintService.java#L56 you can see how it sends stories to the mirrorgate server. The next method is also used to delete them if needed.

This is the model used to send the data to the mirrorgate server:
https://github.com/BBVA/mirrorgate-jira-stories-collector/blob/master/src/main/java/com/bbva/arq/devops/ae/mirrorgate/collectors/jira/dto/IssueDTO.java

Note that all the information (Sprints, Project, etc) is denormalized inside issues. That's why if needed you can recover all the issues that need to be changed, when you detect a sprint metadata change https://github.com/BBVA/mirrorgate-jira-stories-collector/blob/master/src/main/java/com/bbva/arq/devops/ae/mirrorgate/collectors/jira/api/SprintService.java#L83 

If you need to make incremental batches, mirrorgate exposes an API where you can save the date of the collectors last succesful execution:
https://github.com/BBVA/mirrorgate-jira-stories-collector/blob/master/src/main/java/com/bbva/arq/devops/ae/mirrorgate/collectors/jira/api/CollectorService.java#L56

Let us know if this is enough for you to start playing with the API. Also if you come to some kind of integration with TFS we will very glad to ear about your solution.

**Comment by lwasylow** [comment]
Superb, I will have a read and play around.
